baseURL = "https://ulsterworldly.com/"
languageCode = "en-us"
title = "Ulster Worldly"
theme = "westminsterhist"
Copyright = "2018 Tim Hopper"

[pagination]
pagerSize = 10

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag = "tags"
  people = "people"
  church = "churches"

[params]
disable_sri = true
feedpress = "https://feedpress.me/ulsterworldly"
truncate = false
description = "Stories from the history of presbyterianism in America and beyond."
long_description = """
Anecdotes, original sources, facts, and figures from presbyterian history.
Many of these stories come from my own family history with presbyterianism and missions."""
author = "Tim Hopper"
custom_navbar = true
comments = false
