[build]
  publish = "public"
  command = "cd themes/westminsterhist && npm install && npm run build && cd ../.. && hugo --enableGitInfo"

[build.environment]
  HUGO_VERSION = "0.139.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "staging"

[context.branch-deploy.environment]
  HUGO_ENV = "staging"
